### ISSUE TITLE
Schema function doesn't exist on SchemaAssertion [QUESTION]

### ISSUE THREAD

**Issue by denitsa-md** [sixlive/laravel-json-schema-assertions#17]
I'm just looking at the master branch in here (haven't installed it) and I'm wondering how is it possible that the Service provider calls a `schema` function on the SchemaAssertion:

https://github.com/sixlive/laravel-json-schema-assertions/blob/master/src/ServiceProvider.php#L27

But there is no `schema` function in the class.

https://github.com/sixlive/laravel-json-schema-assertions/blob/master/src/SchemaAssertion.php

Maybe I'm missing something?

**Comment by sixlive** [comment]
Hmmm, this does indeed look odd. I'll look into this.

**Comment by ce-brex** [comment]
The SchemaAssertion being called in the ServiceProvider is the class provided by https://github.com/sixlive/json-schema-assertions/blob/master/src/SchemaAssertion.php (dependency included in composer.json), not the SchemaAssertion class in this package.
