### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by emanuel-jacob** [sixlive/laravel-json-schema-assertions#21]
## What are the steps to reproduce this issue?

1. Try using composer to install the package with laravel-8

## What happens?
fail 
illuminate/support: ^7.0
phpunit/phpunit: ^8.0

## What were you expecting to happen?
install the package

## What versions are you using?
**Operating System:** …  
**Package Version:** …

**Comment by loesalleman** [comment]
It's still not supporting Laravel 8 unfortunately, because Laravel 8 requires phpunit/phpunit ^9.0 (https://laravel.com/docs/8.x/upgrade#updating-dependencies). This package requires phpunit/phpunit ^8.0.
