### ISSUE TITLE
Update PHPUnit Version (11). Typo? 

### ISSUE THREAD

**Issue by sk3ptx** [sixlive/laravel-json-schema-assertions#31]
Typo? Did you mean:
```suggestion
        "phpunit/phpunit": "^9.5|^10.0|^11.0",
```
Because 11.9 does not exist at the moment.
https://github.com/sebastianbergmann/phpunit/releases

_Originally posted by @sk3ptx in https://github.com/sixlive/laravel-json-schema-assertions/pull/30#discussion_r1716768004_

**Comment by sixlive** [comment]
OMG I'm so sorry about that! Fixed! https://github.com/sixlive/laravel-json-schema-assertions/releases/tag/v4.3.1
