### ISSUE TITLE
Update PHPUnit Version (11). Another Typo.  

### ISSUE THREAD

**Issue by sk3ptx** [sixlive/laravel-json-schema-assertions#32]
https://github.com/sixlive/laravel-json-schema-assertions/blob/18790dc9923fdffa7be82c79d84d3444db3684b1/composer.json#L24

Sorry, found another typo. 🤷‍♀️
```suggestion
       "phpunit/phpunit": "^9.5|^10.0|^11.0",
```

**Comment by sixlive** [comment]
HOW?!?! OMG I'm so embarrassed. Fixed https://github.com/sixlive/laravel-json-schema-assertions/releases/tag/v4.3.2
