### ISSUE TITLE
Nullable not working

### ISSUE THREAD

**Issue by devronhansen** [sixlive/laravel-json-schema-assertions#9]
Hey, thanks for the awesome Package. Unfortunately i've ran into a problem.

## What are the steps to reproduce this issue?

1. set a property to nullable
```json
{
  ...
 "properties": {
     "address": {
        "type": "object",
        "nullable": true,
        "properties": { ...}
     }
  }
}
```
2. Run test in which the address is null
3. Get error that Object was expected, but null received.

## What happens?
Error: Object expected, null received at ...

## What were you expecting to happen?
Green test

If i run the same test with an address or if set the address to an empty object the test returns green. 
Additionally nullable works correctly in redoc.
So for some reason nullable doesn't seem to work.

Thanks for any help.

**Comment by sixlive** [comment]
I've got a bunch going on over the next two days, I'll schedule some time to take a look at this. Will likely be closer to Wednesday.

**Comment by sixlive** [comment]
Sorry, I totally forgot about this. 

So I was looking at it this morning. I think this might be behaving correctly. 

What draft version of JSON Schema are you using?

You are specifying that it must be of type `object` but if it can be null it needs to be both.

```json
{
 "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "address": {
      "type": ["object", "null"],
      "properties": {
        "street": {
          "type": "string"
        }
      }
    }
  }
}
```

With that schema the following passes validation.

```json
{
  "address": null,
}
```

You can try running the schema through https://www.jsonschemavalidator.net and see if it passes validation or not.

I'm going to close this issue for now but if we find that there is a problem I can re-open it.

**Comment by cbaconnier** [comment]
I have the same problem. I don't know a lot about the draft JSON Schema nor OpenApi. But it seem's that OpenAPI 3 expect a string, not an array. To specify `null` it uses the `nullable` property.

As a date of today, this is the only difference I have noticed between both (draft JSON Schema and OpenApi 3) 
And it's kinda a problem when you want to use the same json for both usage: Documentation + Assertions
https://swagger.io/docs/specification/data-models/data-types/#null

**Comment by sixlive** [comment]
There is actually a lot of divergence between JSON Schema and OpenAPI.

* https://philsturgeon.uk/api/2018/03/30/openapi-and-json-schema-divergence/
* https://philsturgeon.uk/api/2018/04/13/openapi-and-json-schema-divergence-solved/

I hand roll my OpenAPI docs and use external references to JSON Schemas that are independent. Since I use a design/document first approach this works out well and allows me to do assertions against the Schemas independently. I then compile them together using [Speccy](https://github.com/wework/speccy).
